### ISSUE TITLE
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5531 

### ISSUE THREAD

**Issue by Balakrishna1** [alexrainman/ModernHttpClient#78]
Hi Team, My android app getting crashed after updating the ModernHttpClient package to the latest.
Please help me out in this.

Thanks in Advance.

Here is the log.

"OkHttp https://eu.company.com/..." prio=10 tid=72 Native
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] | group="" sCount=1 dsCount=0 flags=1 obj=0x13540000 self=0xca6b4000
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] | sysTid=5602 nice=-4 cgrp=default sched=0/0 handle=0xbf8e6970
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] | state=S schedstat=( 7066721 14619057 31 ) utm=0 stm=0 core=2 HZ=100
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] | stack=0xbf7e4000-0xbf7e6000 stackSize=1038KB
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] | held mutexes=
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] kernel: poll_schedule_timeout+0x44/0x70
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] kernel: do_sys_poll+0x47e/0x550
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] kernel: compat_SyS_ppoll+0x182/0x1b0
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] kernel: do_fast_syscall_32+0x9c/0x170
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] kernel: sysenter_flags_fixed+0x8/0x12
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] native: #00 pc 00000bc9 [vdso] (__kernel_vsyscall+9)
01-28 13:48:31.787 F/zygote ( 5457): runtime.cc:492] native: #01 pc 00073986 /system/lib/libc.so (__ppoll+38)
01-28 13:48:31.789 F/zygote ( 5457): runtime.cc:492] at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
01-28 13:48:31.789 F/zygote ( 5457): runtime.cc:492] at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
01-28 13:48:31.789 F/zygote ( 5457): runtime.cc:492] at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
01-28 13:48:31.789 F/zygote ( 5457): runtime.cc:492] at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
01-28 13:48:31.789 F/zygote ( 5457): runtime.cc:492] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-28 13:48:31.789 F/zygote ( 5457): runtime.cc:492] at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-28 13:48:31.876 W/google-breakpad( 5457): ### ### ### ### ### ### ### ### ### ### ### ### ###
01-28 13:48:31.876 W/google-breakpad( 5457): Chrome build fingerprint:
01-28 13:48:31.876 W/google-breakpad( 5457): 1.1.159
01-28 13:48:31.876 W/google-breakpad( 5457): 11159
01-28 13:48:31.876 W/google-breakpad( 5457): ### ### ### ### ### ### ### ### ### ### ### ### ###
01-28 13:48:31.877 F/libc ( 5457): Fatal signal 6 (SIGABRT), code -6 in tid 5531 (Thread Pool Wor)
[bug.txt](https://github.com/alexrainman/ModernHttpClient/files/5908781/bug.txt)

**Comment by alexrainman** [comment]
Can you provide a demo reproducing the issue?

**Comment by Physikbuddha** [comment]
Check if your project is targeting the correct platform you're trying to run on.
Most probably you're trying to run on an x86_64 emulator, but your supported platforms are armeabi-v7a;arm64-v8a;x86 only.

Check <AndroidSupportedAbis> in your csproj. If you're building for an x64 emulator, add x86_64. If you're building for an x86 emulator, add x86 (if it's missing).
